businesses = [
    {
        "address": "123 Main Street, New York, NY",
        "name": "Black Sheep Brasserie",
        "rating": 4.37,
        "delivery_fee": 2.15,
        "price_range": "$$$",
        "cuisine": "French",
    },
    {
        "address": "456 Oak Avenue, Los Angeles, CA",
        "name": "Breakfast Bites",
        "rating": 3.82,
        "delivery_fee": 3.90,
        "price_range": "$$",
        "cuisine": "Breakfast",
    },
    {
        "address": "789 Maple Road, Chicago, IL",
        "name": "The Pit Boss",
        "rating": 4.68,
        "delivery_fee": 1.50,
        "price_range": "$$$$",
        "cuisine": "BBQ",
    },
    {
        "address": "101 Elm Street, San Francisco, CA",
        "name": "Kobe Kobe",
        "rating": 4.92,
        "delivery_fee": 2.80,
        "price_range": "$$",
        "cuisine": "Sushi",
    },
    {
        "address": "246 Pine Avenue, Miami, FL",
        "name": "The Underground",
        "rating": 4.05,
        "delivery_fee": 4.10,
        "price_range": "$$",
        "cuisine": "Pizza",
    },
    {
        "address": "789 Cherry Lane, Houston, TX",
        "name": "Chinese Garden",
        "rating": 4.50,
        "delivery_fee": 3.25,
        "price_range": "$$$",
        "cuisine": "Chinese",
    },
    {
        "address": "654 Walnut Drive, Seattle, WA",
        "name": "Octoburgers",
        "rating": 4.20,
        "delivery_fee": 2.50,
        "price_range": "$$",
        "cuisine": "Burgers",
    },
    {
        "address": "321 Cedar Street, Austin, TX",
        "name": "Mexi-Casa",
        "rating": 4.75,
        "delivery_fee": 2.00,
        "price_range": "$$$",
        "cuisine": "Mexican",
    },
    {
        "address": "987 Willow Court, Orlando, FL",
        "name": "Vanilla Cone",
        "rating": 4.88,
        "delivery_fee": 1.80,
        "price_range": "$",
        "cuisine": "Ice Cream & Frozen Yogurt",
    },
    {
        "address": "841 Braintree Avenue, Boston, MA",
        "name": "Bon Appétit Paris",
        "rating": 4.88,
        "delivery_fee": 2.99,
        "price_range": "$$",
        "cuisine": "French",
    },
    {
        "address": "789 Market Street, San Francisco, CA",
        "name": "Red Lantern Restaurant & Lounge",
        "rating": 4.60,
        "delivery_fee": 2.30,
        "price_range": "$$$",
        "cuisine": "Chinese",
    },
    {
        "address": "654 Broadway Avenue, New York, NY",
        "name": "Juicy Lucy’s",
        "rating": 4.15,
        "delivery_fee": 3.80,
        "price_range": "$$",
        "cuisine": "Burgers",
    },
    {
        "address": "543 Rose Street, Boston, MA",
        "name": "The Family Bean",
        "rating": 4.10,
        "delivery_fee": 3.75,
        "price_range": "$$",
        "cuisine": "Coffee & Tea",
    },
    {
        "address": "321 Harbor Road, Miami, FL",
        "name": "Sushi Tower",
        "rating": 4.80,
        "delivery_fee": 2.50,
        "price_range": "$$$",
        "cuisine": "Sushi",
    },
    {
        "address": "987 Park Lane, Los Angeles, CA",
        "name": "Bread Bazar",
        "rating": 4.92,
        "delivery_fee": 1.80,
        "price_range": "$$",
        "cuisine": "Bakery",
    },
    {
        "address": "246 Vine Street, Chicago, IL",
        "name": "Spicy Pig Hideout",
        "rating": 4.35,
        "delivery_fee": 3.90,
        "price_range": "$$$",
        "cuisine": "BBQ",
    },
    {
        "address": "543 Grove Drive, Seattle, WA",
        "name": "Mugs and Spoons",
        "rating": 4.40,
        "delivery_fee": 3.20,
        "price_range": "$$",
        "cuisine": "Coffee & Tea",
    },
    {
        "address": "101 Maple Lane, Houston, TX",
        "name": "Broken Spanish",
        "rating": 4.75,
        "delivery_fee": 2.10,
        "price_range": "$$$",
        "cuisine": "Mexican",
    },
    {
        "address": "789 Ocean View, Orlando, FL",
        "name": "Sub Zero Ice Cream Bars",
        "rating": 4.25,
        "delivery_fee": 2.95,
        "price_range": "$",
        "cuisine": "Ice Cream & Frozen Yogurt",
    },
    {
        "address": "456 River Road, Austin, TX",
        "name": "The River Bar",
        "rating": 4.50,
        "delivery_fee": 3.00,
        "price_range": "$$$",
        "cuisine": "Alcohol",
    },
    {
        "address": "123 Meadow Lane, Boston, MA",
        "name": "Round Table Pizza",
        "rating": 4.10,
        "delivery_fee": 3.70,
        "price_range": "$$",
        "cuisine": "Pizza",
    },
    {
        "address": "789 Oak Street, San Francisco, CA",
        "name": "Silk Road",
        "rating": 4.40,
        "delivery_fee": 2.25,
        "price_range": "$$$",
        "cuisine": "Chinese",
    },
    {
        "address": "654 Broadway Avenue, New York, NY",
        "name": "Shinsen Sunrise",
        "rating": 4.15,
        "delivery_fee": 3.80,
        "price_range": "$$",
        "cuisine": "Sushi",
    },
    {
        "address": "321 Sea View, Miami, FL",
        "name": "Tapa Toro",
        "rating": 4.80,
        "delivery_fee": 2.50,
        "price_range": "$$$",
        "cuisine": "Mexican",
    },
    {
        "address": "987 Maple Lane, Los Angeles, CA",
        "name": "Bread & Butter",
        "rating": 4.92,
        "delivery_fee": 1.80,
        "price_range": "$$",
        "cuisine": "Bakery",
    },
    {
        "address": "246 Pine Street, Chicago, IL",
        "name": "Head-to-Tail",
        "rating": 4.35,
        "delivery_fee": 3.90,
        "price_range": "$$$",
        "cuisine": "BBQ",
    },
    {
        "address": "543 River Road, Seattle, WA",
        "name": "Solid Ground Cafe",
        "rating": 4.40,
        "delivery_fee": 3.20,
        "price_range": "$$",
        "cuisine": "Coffee & Tea",
    },
    {
        "address": "789 Ocean View, Orlando, FL",
        "name": "Dairy Lady",
        "rating": 4.25,
        "delivery_fee": 2.95,
        "price_range": "$",
        "cuisine": "Ice Cream & Frozen Yogurt",
    },
    {
        "address": "456 Meadow Lane, Austin, TX",
        "name": "Beefcake's Burgers",
        "rating": 4.50,
        "delivery_fee": 3.00,
        "price_range": "$$",
        "cuisine": "Burgers",
    },
    {
        "address": "123 Market Street, Boston, MA",
        "name": "A Slice of Americana",
        "rating": 4.10,
        "delivery_fee": 3.70,
        "price_range": "$$",
        "cuisine": "Pizza",
    },
]
